AspMvcWebshop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspMvcWebshop.Models;
using AspMvcWebshop.ViewModels;


namespace AspMvcWebshop.Controllers
{
    public class ShoppingCartController : Controller
    {
        StoreEntities storeDB = new StoreEntities();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedProduct = storeDB.Products
                .Single(product => product.productId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string productName = storeDB.Carts
                .Single(item => item.RecordId == id).Product.Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
	}
}

AspMvcWebshop/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspMvcWebshop.Models;

namespace AspMvcWebshop.Controllers
{
    public class StoreController : Controller
    {
        StoreEntities storeDB = new StoreEntities();

        //
        // GET: /Store/
        public ActionResult Index()
        {
            var categories = storeDB.Categories.ToList();        
            return View(categories);
        }
        //
        // GET: /Store/Browse
        //returns NULL?????
        public ActionResult Browse(string category)
        {
            //prevent Javascript - HtmlEncode
            var categoryModel = storeDB.Categories.Include("Products")
                .SingleOrDefault(c => c.Name.Contains(category));
                //lambda expression, we want a single object that it's
                //name matches the defined value.                
            
            return View(categoryModel);
        }

        //
        // GET: /Store/Details/5
        public ActionResult Details(int id)
        {
            var product = storeDB.Products.Find(id);

            return View(product);
        }

        //
        // GET: /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult CategoryMenu()
        {
            var genres = storeDB.Categories.ToList();
            return PartialView(genres);
        }

        //partial views logic
        [ChildActionOnly]
        public ActionResult AdminMenu()
        {
            if (User.IsInRole("Administrator")) // TODO: Remove magic string
            {
                return PartialView("AdminMenu");
            }
            return new EmptyResult();
        }

        [ChildActionOnly]
        public ActionResult GuestMenu()
        {
            if (!User.Identity.IsAuthenticated) // TODO: Remove magic string
            {
                return PartialView("GuestMenu");
            }
            return new EmptyResult();
        }

        [ChildActionOnly]
        public ActionResult RegisteredUser()
        {
            if (User.Identity.IsAuthenticated && !User.IsInRole("Administrator")) // TODO: Remove magic string
            {
                return PartialView("RegisteredUserMenu");
            }
            return new EmptyResult();
        }  
    }
}

AspMvcWebshop/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AspMvcWebshop.Models;
using System.IO;
using System.Web.Helpers;

namespace AspMvcWebshop.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StoreManagerController : Controller
    {
        private StoreEntities db = new StoreEntities();

        // GET: /StoreManager/
        public ActionResult Index()
        {            
            var products = db.Products.Include(p => p.Brand).Include(p => p.Category);
            return View(products.ToList());
        }

        // GET: /StoreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: /StoreManager/Create
        public ActionResult Create()
        {
            ViewBag.brandId = new SelectList(db.Brands, "BrandId", "Name");
            ViewBag.categoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: /StoreManager/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="productId,categoryId,brandId,Name,Price,ProductImg")] Product product)
        {
            if (ModelState.IsValid)
            {
                WebImage ProductImg = null;
                var newFileName = "";
                var imagePath = "";
                //RIJEŠITI NESTED IF
                //zašto ne prihvaća HttpPostedFileBase tip??
                if (ProductImg != null)
                {
                    newFileName = Guid.NewGuid().ToString() + "_" +
                        Path.GetFileName(ProductImg.FileName);
                    imagePath = @"~\Content\Images\" + newFileName;

                    ProductImg.Save(@"~\" + imagePath);
                }
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.brandId = new SelectList(db.Brands, "BrandId", "Name", product.brandId);
            ViewBag.categoryId = new SelectList(db.Categories, "CategoryId", "Name", product.categoryId);
            return View(product);
        }

        // GET: /StoreManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.brandId = new SelectList(db.Brands, "BrandId", "Name", product.brandId);
            ViewBag.categoryId = new SelectList(db.Categories, "CategoryId", "Name", product.categoryId);
            return View(product);
        }

        // POST: /StoreManager/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="productId,categoryId,brandId,Name,Price,ProductImg")] Product product)
        {
            if (ModelState.IsValid)
            {
                WebImage ProductImg = null;
                var newFileName = "";
                var imagePath = "";
                //RIJEŠITI NESTED IF
                //zašto ne prihvaća HttpPostedFileBase tip??
                if (ProductImg != null)
                {
                    newFileName = Guid.NewGuid().ToString() + "_" +
                        Path.GetFileName(ProductImg.FileName);
                    imagePath = @"~\Content\Images\" + newFileName;

                    ProductImg.Save(@"~\" + imagePath);
                }

                db.Entry(product).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.brandId = new SelectList(db.Brands, "BrandId", "Name", product.brandId);
            ViewBag.categoryId = new SelectList(db.Categories, "CategoryId", "Name", product.categoryId);
            return View(product);
        }

        // GET: /StoreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: /StoreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AspMvcWebshop/Views/Store/AdminMenu.cshtml
<ul>
    <li>
        <a href="#">
            <img src="~/content/img/user-icon.gif" alt="Admin">
            Administrator <img src="~/content/img/down-arrow.gif" alt="Sign In" />
        </a>
        <ul class="admin-menu">
            <li>@Html.ActionLink("Store Management", "Index", "StoreManager")</li>
            <li>@Html.ActionLink("User Management", "", "")</li>
            <li>@Html.ActionLink("Edit Account", "", "")</li>
            <li>@Html.ActionLink("Sign Out", "Logout", "Account")</li>
        </ul>
    </li>
</ul>

AspMvcWebshop/Views/Store/Browse.cshtml
@model AspMvcWebshop.Models.Category

@{
    ViewBag.Title = "Browse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="promo-alt">
    <div id="promo1">
        <h1>Brand new MacBook Pro</h1>
        <p>
            With a special price,
            <span class="bold">today only!</span>
        </p>
        <a href="#" class="secondary-btn">READ MORE</a><img src="../content/../content/img/macbook.png" alt="MacBook Pro" />
    </div> <!-- end promo1-->
    <div id="promo2">
        <h2>
            The iPhone 5 is now<br />
            available in our store.
        </h2><a href="">Read more <img src="../content/img/right-arrow.gif" alt="Read more" /></a>
        <img src="../content/img/iphone.png" alt="iPhone" />
    </div> <!-- end promo2-->
    <div id="promo3">
        <img src="../content/img/thunderbolt.png" alt="Thunderbolt" />
        <h2>
            The 27"<br />
            Thunderbolt display<br />
            simply stunning.
        </h2>
        <a href="#">Read more <img src="../content/img/right-arrow.gif" alt="Read more" /></a>
    </div> <!-- end promo3-->
</section><!-- end promo-alt -->
<section id="main-content" class="clearfix">
    <h2>Browsing Category : @Model.Name</h2>
    <hr />
    <aside id="categories-menu">
        <h3>CATEGORIES</h3>
        @{Html.RenderAction("CategoryMenu", "Store");}
    </aside><!--end categories menu-->

    <div id="listings">
        @foreach (var product in Model.Products)
        {        
        <div class="product">
            <a href="@Url.Action("Details", "Store", new { id = product.productId })">
                <img src="@product.ProductImg" alt="product" class="feature" />
            </a>

            <h3>@Html.ActionLink(product.Name,
                "Details", new { id = product.productId })</h3>

            <p>
                This is a short description.his is a short description.
                his is a short description.his is a short description.
            </p>
            <h5>Availability: <span class="instock">In Stock</span></h5>

            <p>
                <a href="#" class="cart-btn">
                    <span class="price">$499,99</span>
                    <img src="../content/img/white-cart.gif" alt="Add to Cart" />
                    ADD TO CART
                </a>
            </p>

            <p class="wish">
                <a href="">
                    <img src="../content/img/wish.gif" alt="Add to Wishlist" />
                    Add to Wishlist
                </a>
            </p>
        </div>
        }
    </div><!-- end listings -->
</section><!-- end main content -->

<hr />

<section id="pagination">
    <p>
        Page:
        <span class="current">1</span> /
        <a href="#">2</a> /
        <a href="#">3</a>
    </p>
</section><!-- end pagination -->

<hr />

AspMvcWebshop/Views/Store/CategoryMenu.cshtml
@model IEnumerable<AspMvcWebshop.Models.Category>

<ul id="categories">
    @foreach (var category in Model)
    {
        <li>
            @Html.ActionLink(category.Name,
                "Browse", "Store",
                new { Category = category.Name }, null)
    </li>
    }
</ul>

AspMvcWebshop/Views/Store/Details.cshtml
@model AspMvcWebshop.Models.Product

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Product - " + Model.Name;
}

<hr />

<section id="main-content" class="clearfix">
    <div id="product-image">
        <img alt="@Model.Name"
             src="@Model.ProductImg" />
    </div><!-- end product image -->
    <div id="product-details">
        <h1>Product: @Model.Name</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua. Ut enim ad minim veniam, quis nostrud
            exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in
            voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            Excepteur sint occaecat cupidatat non proident, sunt in culpa
            qui officia deserunt mollit anim id est laborum.
        </p>

        <hr />

        @*<form action="#" method="post" enctype="multipart/form-data">*@
            <label for="qty">Qty:</label>
            <input type="text" id="qty" name="qty" value="1" maxlength="2">
            <p class="secondary-cart-btn button">
                <img src="~/content/img/white-cart.gif" alt="Add to cart" />
                @Html.ActionLink("ADD TO CART", "AddToCart",
                    "ShoppingCart", new { id = Model.productId }, "")
            </p>
        @*</form>*@
        <p>
            <a href="#"><img src="~/content/img/wish.gif" alt="Add to Wishlist"> Add to Wishlist</a>
        </p>
    </div><!-- end product details -->
    <div id="product-info">
        <p class="price">HRK @String.Format("{0:F}", Model.Price)</p>
        <p>Availability: <span>In Stock</span></p>
        <p>Product Code: <span>@Model.productId</span></p>
    </div><!-- end product info -->
</section><!-- end main content -->

<hr />

AspMvcWebshop/Views/Store/GuestMenu.cshtml
<ul>
    <li>
        <a href="#">
            <img src="~/content/img/user-icon.gif" alt="Sign In">
            Sign In <img src="~/content/img/down-arrow.gif" alt="Sign In" />
        </a>
        <ul>
            <li>@Html.ActionLink("Sign In", "Login", "Account")</li>
            <li>@Html.ActionLink("Sign Up", "Register", "Account")</li>
        </ul>
    </li>
</ul>

AspMvcWebshop/Views/Store/Index.cshtml
@model IEnumerable<AspMvcWebshop.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Browse categories</h3>
<p>
    Select from @Model.Count() categories: 
</p>
<ul>
    @foreach (var category in Model)
    {
        <li>
            @Html.ActionLink(category.Name,
"Browse", new { category = category.Name })
    </li>
    }
</ul>

AspMvcWebshop/Views/Store/RegisteredUserMenu.cshtml
<ul>
    <li>
        <a href="#">
            <img src="~/content/img/user-icon.gif" alt="Admin">
            @User.Identity.Name <img src="~/content/img/down-arrow.gif" alt="Sign In" />
        </a>
        <ul class="admin-menu">
            <li>@Html.ActionLink("Order History", "", "")</li>
            <li>@Html.ActionLink("Wishlist", "", "")</li>
            <li>@Html.ActionLink("Preferences", "Manage", "Account")</li>
            <li>@Html.ActionLink("Sign Out", "Logout", "Account")</li>
        </ul>
    </li>
</ul>